twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        title: "My Space"
        cats: '@App\Twig\CatsExtension'
        user_profile_picture_directory: '%user_profile_picture_directory%'