home:
    path: /
    controller: App\Controller\HomeController::index

admin_home:
    path: /my-space
    controller: App\Controller\Admin\AdminController::index

account:
    path: /my-space/profil
    controller: App\Controller\UserController::index



